"""
Main Orchestration Controller for Nordic Micro-Cap Stock Screener & Trading Bot.

Dual-Pipeline "Core & Satellite" Production MVP Daemon:
1. Initialization:
   - Ingests master Nordic micro/small-cap universe (MarketCap <= 300M EUR) from `data/nordnet_universe.csv`.
   - Initializes SQLite state database (`data/screener_state.db`).
   - Configures and verifies SMTP email alerts (`EmailClient`).
   - Initializes strategy-aware `ExitManager` for tracking paper positions.

2. Screening Execution Loop (Every 15 minutes during market hours / scheduled interval):
   - Step A (Scrape): Ingests latest regulatory filings and PRs across Nordic wires.
   - Step B (Route): Intelligently routes documents to TRASH, CORE, or SATELLITE.
   - Step C (NLP Analysis): Evaluates LLM prompt (Risk Screen -> Quality/Catalyst check).
   - Step D (Quant Filter & Sizing): Verifies bid-ask spread (< 4.0%), liquidity, and calculates
     Fractional Half-Kelly (Satellite) vs Equal Weight Conviction (Core) position sizing.
   - Step E (Execute & Alert):
     * Opens paper position in `data/open_positions.csv`.
     * Logs alert to `data/screener_alerts.csv`.
     * Dispatches structured HTML/plain-text `[CORE ALERT]` or `[SATELLITE ALERT]` email.

3. End-of-Day (EOD) Maintenance (Runs daily at 19:00):
   - Calls `exit_manager.check_exits()` to evaluate all active positions.
   - SATELLITE: Executes on +25% Take Profit, 15% Trailing Stop, 15% Hard Stop, 45d Time Decay.
   - CORE: Bypasses daily volatility; exits only on quarterly fundamental breakdown.
   - Archives closed trades to `data/trade_history.csv` and dispatches `[SELL ALERT]` emails.
"""

from __future__ import annotations

import argparse
import csv
import logging
import os
import re
import sys
import time
from datetime import datetime, date, timezone
from pathlib import Path
from typing import List, Dict, Any, Optional, Union

from dotenv import load_dotenv

# Load .env variables
load_dotenv()

# Reconfigure stdout/stderr for cross-platform encoding compatibility (Windows cp1252 fix)
if hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass
if hasattr(sys.stderr, "reconfigure"):
    try:
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

# Ensure parent directory is in sys.path
_current_dir = Path(__file__).resolve().parent
BASE_DIR = _current_dir.parent if _current_dir.name == "screener" else _current_dir
if str(BASE_DIR) not in sys.path:
    sys.path.insert(0, str(BASE_DIR))

from screener.config import ScreenerConfig, get_dynamic_interval
from screener.models import FeedItem, StrategyType, DocumentPayload
from screener.scraper_module import NasdaqHelsinkiScraper, fetch_latest_releases
from screener.state_manager import init_db, is_processed, mark_as_processed
from screener.nlp_analyzer import (
    analyze_text,
    analyze_core_fundamentals,
    analyze_satellite_catalysts,
    route_document,
    classify_release_strategy,
    FinancialNLPAnalyzer,
)
from screener.quant_engine import QuantitativeRiskEngine, check_liquidity_and_spread
from screener.exit_manager import ExitManager
from screener.web_verifier import WebSearchVerifier
from clients.email_client import EmailClient, send_alert, send_sell_alert

# Logging configuration
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)]
)
logger = logging.getLogger("screener.main_controller")

DEFAULT_ALERTS_CSV = BASE_DIR / "data" / "screener_alerts.csv"
DEFAULT_UNIVERSE_CSV = BASE_DIR / "data" / "nordnet_universe.csv"
DEFAULT_OPEN_POSITIONS_CSV = BASE_DIR / "data" / "open_positions.csv"
DEFAULT_TRADE_HISTORY_CSV = BASE_DIR / "data" / "trade_history.csv"


def load_nordnet_universe(csv_path: Optional[Path | str] = None) -> Dict[str, Any]:
    """
    Loads master Nordic micro/small-cap universe generated by universe_builder.py.
    Provides fast indexed lookups by Ticker_YF, base ticker, and company name.
    """
    path = Path(csv_path or DEFAULT_UNIVERSE_CSV)
    universe_map: Dict[str, Dict[str, Any]] = {}
    base_ticker_map: Dict[str, Dict[str, Any]] = {}
    name_map: Dict[str, Dict[str, Any]] = {}

    if not path.exists():
        logger.warning(f"Nordnet universe CSV not found at {path}. Operating without pre-filtered universe constraints.")
        return {
            "by_ticker_yf": {},
            "by_base_ticker": {},
            "by_name": {},
            "total_count": 0,
            "path": str(path),
        }

    try:
        with open(path, "r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                ticker_yf = row.get("Ticker_YF", "").strip().upper()
                name = row.get("Name", "").strip()
                market = row.get("Market", "").strip()
                market_cap = float(row.get("MarketCap_EUR", 0.0) or 0.0)

                if not ticker_yf:
                    continue

                entry = {
                    "Ticker_YF": ticker_yf,
                    "Name": name,
                    "Market": market,
                    "MarketCap_EUR": market_cap,
                }

                universe_map[ticker_yf] = entry

                # Map base ticker (e.g. "FARON" from "FARON.HE")
                base_ticker = ticker_yf.split(".")[0]
                base_ticker_map[base_ticker] = entry

                # Map normalized company name
                if name:
                    clean_name = re.sub(r"\b(oyj|oy|plc|ab|asa|a/s|as|corp|inc)\b", "", name, flags=re.IGNORECASE).strip().lower()
                    name_map[clean_name] = entry
                    name_map[name.lower()] = entry

        logger.info(f"Loaded master universe with {len(universe_map)} stocks from {path}")
    except Exception as e:
        logger.error(f"Error loading universe from {path}: {e}")

    return {
        "by_ticker_yf": universe_map,
        "by_base_ticker": base_ticker_map,
        "by_name": name_map,
        "total_count": len(universe_map),
        "path": str(path),
    }


def match_universe_item(
    item: FeedItem,
    universe_data: Dict[str, Any],
) -> Optional[Dict[str, Any]]:
    """
    Matches a scraped news item against the loaded master universe.
    Returns matched universe record or None if the stock is not in the tradable micro-cap pool.
    """
    if not universe_data or universe_data.get("total_count", 0) == 0:
        return {
            "Ticker_YF": item.ticker or "",
            "Name": item.company_name or item.title,
            "Market": "Unknown",
            "MarketCap_EUR": 0.0,
        }

    by_ticker_yf = universe_data.get("by_ticker_yf", {})
    by_base_ticker = universe_data.get("by_base_ticker", {})
    by_name = universe_data.get("by_name", {})

    # 1. Match by item.ticker
    if item.ticker:
        tick_upper = item.ticker.upper().strip()
        if tick_upper in by_ticker_yf:
            return by_ticker_yf[tick_upper]
        base_tick = tick_upper.split(".")[0]
        if base_tick in by_base_ticker:
            return by_base_ticker[base_tick]

    # 2. Match by item.company_name
    if item.company_name:
        comp_clean = re.sub(r"\b(oyj|oy|plc|ab|asa|a/s|as|corp|inc)\b", "", item.company_name, flags=re.IGNORECASE).strip().lower()
        if comp_clean in by_name:
            return by_name[comp_clean]
        if item.company_name.lower().strip() in by_name:
            return by_name[item.company_name.lower().strip()]

    # 3. Match title with word boundary regex
    title_lower = (item.title or "").lower()
    for name_key, entry in by_name.items():
        if len(name_key) >= 4:
            pattern = rf"\b{re.escape(name_key)}\b"
            if re.search(pattern, title_lower):
                return entry

    for base_tick, entry in by_base_ticker.items():
        if len(base_tick) >= 3:
            pattern = rf"(?:\[|\(|\b){re.escape(base_tick.lower())}(?:\]|\)|\b|:)"
            if re.search(pattern, title_lower):
                return entry

    return None


class ScreenerPipelineController:
    """Production MVP Orchestration Daemon for Core & Satellite Trading System."""

    def __init__(
        self,
        config: Optional[ScreenerConfig] = None,
        alerts_csv_path: Optional[Path | str] = None,
        universe_csv_path: Optional[Path | str] = None,
        open_positions_path: Optional[Path | str] = None,
        trade_history_path: Optional[Path | str] = None,
        openrouter_api_key: Optional[str] = None,
        total_portfolio_eur: float = 10_000.0,
        enforce_universe: bool = True,
        email_client: Optional[EmailClient] = None,
    ):
        self.config = config or ScreenerConfig.from_env()
        self.alerts_csv_path = Path(alerts_csv_path or DEFAULT_ALERTS_CSV)
        self.alerts_csv_path.parent.mkdir(parents=True, exist_ok=True)
        self.universe_csv_path = Path(universe_csv_path or DEFAULT_UNIVERSE_CSV)
        self.open_positions_path = Path(open_positions_path or DEFAULT_OPEN_POSITIONS_CSV)
        self.trade_history_path = Path(trade_history_path or DEFAULT_TRADE_HISTORY_CSV)
        self.enforce_universe = enforce_universe
        self.total_portfolio_eur = float(os.getenv("PORTFOLIO_TOTAL_CAPITAL_EUR", str(total_portfolio_eur)))

        if openrouter_api_key is not None:
            self.api_key = openrouter_api_key
        else:
            self.api_key = os.getenv("OPENROUTER_API_KEY") or os.getenv("OPENAI_API_KEY")

        # 1. Initialize SQLite State Database
        init_db(self.config.db_path)
        logger.info(f"State database initialized at {self.config.db_path}")

        # 2. Check API key status
        if not self.api_key:
            logger.warning("OPENROUTER_API_KEY is not set. Operating with deterministic Finnish keyword NLP engine.")
        else:
            logger.info("OpenRouter API key detected and loaded.")

        # 3. Load Master Stock Universe
        self.universe_data = load_nordnet_universe(self.universe_csv_path) if self.enforce_universe else {}

        # 4. Initialize Core Components
        self.scraper = NasdaqHelsinkiScraper(self.config)
        self.quant_engine = QuantitativeRiskEngine(self.config)
        self.web_verifier = WebSearchVerifier(api_key=self.api_key)
        self.exit_manager = ExitManager(
            open_positions_path=self.open_positions_path,
            trade_history_path=self.trade_history_path,
        )
        self.email_client = email_client or EmailClient()

        if self.email_client.is_configured:
            logger.info(f"Email Alerter configured (SMTP: {self.email_client.smtp_server}:{self.email_client.smtp_port} -> {self.email_client.email_to})")
        else:
            logger.info("Email Alerter unconfigured (operating in silent notification mode).")

    def calculate_sizing(self, strategy_type: str, ticker: str, min_trade_eur: float = 500.0) -> Dict[str, Any]:
        """
        Computes capital allocation and position sizing based on Strategy Type.
        - SATELLITE: Fractional Half-Kelly model on the 25% satellite pool.
        - CORE: Conviction Equal-Weight allocation (15%) on the 75% core pool.
        """
        if strategy_type == StrategyType.CORE.value:
            core_pool = self.total_portfolio_eur * self.config.core_capital_pct
            target_pct = 0.15  # 15% equal weight per Core position
            allocation_eur = max(min_trade_eur, round(core_pool * target_pct, 2))
            return {
                "strategy_type": StrategyType.CORE.value,
                "capital_pool_eur": round(core_pool, 2),
                "allocation_pct_of_pool": target_pct * 100.0,
                "recommended_allocation_eur": allocation_eur,
                "kelly_fraction": None,
                "sizing_model": "Core Equal Weight (15% of Core Pool)",
            }
        else:
            satellite_pool = self.total_portfolio_eur * self.config.satellite_capital_pct
            # Fractional Half-Kelly: Win=60%, TP=+25%, SL=-15%, b=1.667 -> Full Kelly=0.36 -> Half Kelly=0.18
            p = 0.60
            b = 0.25 / 0.15
            full_kelly = max(0.0, (p * (b + 1.0) - 1.0) / b)
            half_kelly = full_kelly * 0.5
            allocation_eur = max(min_trade_eur, round(satellite_pool * half_kelly, 2))
            return {
                "strategy_type": StrategyType.SATELLITE.value,
                "capital_pool_eur": round(satellite_pool, 2),
                "allocation_pct_of_pool": round(half_kelly * 100.0, 1),
                "recommended_allocation_eur": allocation_eur,
                "kelly_fraction": round(half_kelly, 3),
                "sizing_model": f"Fractional Half-Kelly ({half_kelly*100:.1f}% of Satellite Pool)",
            }

    def record_open_position(
        self,
        candidate: Dict[str, Any],
        entry_price: float,
        shares: int,
        position_value: float,
    ) -> bool:
        """
        Records a newly executed trade to `data/open_positions.csv`.
        Skips if position for this ticker is already open.
        """
        ticker = candidate.get("ticker", "").strip().upper()
        if not ticker:
            return False

        open_positions = self.exit_manager.load_open_positions()
        existing_tickers = {p["Ticker"].upper() for p in open_positions}

        if ticker in existing_tickers:
            logger.info(f"[EXISTS] Position already open for {ticker}. Skipping duplicate position recording.")
            return False

        today_str = date.today().strftime("%Y-%m-%d")
        new_pos = {
            "Ticker": ticker,
            "EntryDate": today_str,
            "EntryPrice": round(entry_price, 4),
            "HighestPrice": round(entry_price, 4),
            "Shares": shares,
            "PositionValue": round(position_value, 2),
            "Strategy_Type": candidate.get("strategy_type", "SATELLITE"),
        }

        open_positions.append(new_pos)
        self.exit_manager.save_open_positions(open_positions)
        logger.info(f"💎 [POSITION OPENED] Recorded {ticker} ({candidate.get('strategy_type')}) in {self.open_positions_path}: {shares} shs @ {entry_price:.2f}€ = {position_value:.2f}€")
        return True

    def run_screening_cycle(self, dry_run: bool = False) -> List[Dict[str, Any]]:
        """
        Executes one full screening pass across all active Nordic feeds:
        Step A: Scrape news & PRs.
        Step B: Match universe and route document (TRASH, CORE, SATELLITE).
        Step C: NLP analysis and quality validation.
        Step D: Quant friction filter & sizing.
        Step E: Execute trade (open_positions.csv) and send alert.
        """
        logger.info("=" * 75)
        logger.info(">>> STARTING SCREENING PASS (Nordic Micro-Cap Universe) <<<")
        logger.info(
            f"Universe: {self.universe_data.get('total_count', 0)} stocks | "
            f"Capital Allocation: Core={self.config.core_capital_pct*100:.0f}% | "
            f"Satellite={self.config.satellite_capital_pct*100:.0f}%"
        )
        logger.info("=" * 75)
        start_time = time.time()

        # Step A: Scrape latest releases
        try:
            releases: List[FeedItem] = fetch_latest_releases(self.config)
        except Exception as e:
            logger.error(f"Failed to fetch releases from feeds: {e}")
            return []

        if not releases:
            logger.info("No releases returned from feeds. Pass complete.")
            return []

        candidates_found: List[Dict[str, Any]] = []
        processed_count = 0
        skipped_count = 0
        trash_count = 0
        universe_discard_count = 0

        for release in releases:
            article_id = release.guid or release.link
            title = release.title
            pub_date = release.published_at.isoformat() if release.published_at else ""

            # Check SQLite state
            if is_processed(article_id, self.config.db_path):
                skipped_count += 1
                continue

            # Step B: Match Universe
            matched_stock = match_universe_item(release, self.universe_data)
            if self.universe_data.get("total_count", 0) > 0 and matched_stock is None:
                universe_discard_count += 1
                if not dry_run:
                    mark_as_processed(article_id, title, pub_date, self.config.db_path)
                continue

            if matched_stock:
                release.ticker = matched_stock.get("Ticker_YF", release.ticker)
                if matched_stock.get("Name") and not release.company_name:
                    release.company_name = matched_stock["Name"]

            processed_count += 1
            logger.info(f"[{processed_count}] Processing release: {title[:70]}... ({release.ticker or 'N/A'})")

            # Extract Document Content & Route
            try:
                doc = self.scraper.fetch_and_parse_document(release.link)
                header_info = f"{title}\n{release.category or ''}\n{release.summary or ''}"
                full_text = f"{header_info}\n\n{doc.full_combined_text}".strip()

                if not full_text:
                    if not dry_run:
                        mark_as_processed(article_id, title, pub_date, self.config.db_path)
                    continue

                has_pdf = len(doc.pdf_urls) > 0 or bool(doc.pdf_text.strip())
                strategy_route = route_document(
                    news_item=release,
                    has_pdf=has_pdf,
                    full_text=full_text,
                )

                if strategy_route == "TRASH":
                    trash_count += 1
                    if not dry_run:
                        mark_as_processed(article_id, title, pub_date, self.config.db_path)
                    continue

                logger.info(f"--> [ROUTER] Classified as [{strategy_route}]: '{title[:55]}...'")

                # Step C: NLP Analysis
                signals = analyze_text(
                    text_content=full_text,
                    api_key=self.api_key,
                    strategy_type=strategy_route,
                )

            except Exception as e:
                logger.error(f"Error processing release {article_id}: {e}")
                continue

            # Risk Screen Gatekeeper
            safety = signals.get("financial_safety", {})
            going_concern = safety.get("going_concern_risk", signals.get("cash_issue", False))
            dilution_risk = safety.get("dilution_risk_detected", False)
            unsustainable_cash_burn = safety.get("unsustainable_cash_burn", False)
            erratic_pivots = safety.get("erratic_pivots_detected", False)
            safety_failed = going_concern or dilution_risk or unsustainable_cash_burn or erratic_pivots or signals.get("cash_issue", False)

            if safety_failed:
                reasons = []
                if going_concern or signals.get("cash_issue", False):
                    reasons.append("Going Concern / Cash Distress")
                if dilution_risk:
                    reasons.append("Dilution / Reverse Split")
                if unsustainable_cash_burn:
                    reasons.append("Unsustainable Cash Burn (< 12m runway)")
                if erratic_pivots:
                    reasons.append("Erratic Strategic Pivots")
                logger.info(f"[-] Rejected by Risk Screen ({', '.join(reasons)}): {title[:60]}")
                if not dry_run:
                    mark_as_processed(article_id, title, pub_date, self.config.db_path)
                continue

            is_candidate = False
            signal_label = ""
            educational_rationale = signals.get("reasoning", "")

            # Satellite Catalyst Evaluation
            if strategy_route == StrategyType.SATELLITE.value:
                insider_buying_personal = signals.get("insider_buying_personal", signals.get("management_buying", False))
                pos_guidance = signals.get("positive_guidance", False)

                if insider_buying_personal or pos_guidance:
                    signal_types = []
                    if insider_buying_personal:
                        signal_types.append("INSIDER_BUYING")
                    if pos_guidance:
                        signal_types.append("POSITIVE_GUIDANCE")
                    signal_label = " & ".join(signal_types)
                    is_candidate = True
                    logger.info(f"[+] [SATELLITE BUY] {signal_label}: {title}")

            # Core Fundamental Evaluation
            elif strategy_route == StrategyType.CORE.value:
                gross_margin_above_40 = signals.get("gross_margin_above_40", False)
                recurring_revenue = signals.get("recurring_revenue", False)
                rule_of_40_passed = signals.get("rule_of_40_passed", False)
                core_quality_passed = signals.get("core_quality_passed", False)
                matched_profile = signals.get("matched_profile") or signals.get("verdict_details", {}).get("matched_profile", "GROWTH")
                verdict = signals.get("verdict") or signals.get("verdict_details", {}).get("verdict", "")

                if core_quality_passed or verdict == "STRONG BUY" or (gross_margin_above_40 and recurring_revenue and rule_of_40_passed):
                    profile_str = f"PROFILE {matched_profile}" if matched_profile in ("GROWTH", "VALUE") else "10-BAGGER QUALITY"
                    signal_label = f"CORE_{profile_str} (GM: {signals.get('gross_margin_pct', 0):.0f}%, R40: {signals.get('rule_of_40_score', 0):.0f}%)"
                    is_candidate = True
                    logger.info(f"[+] [CORE {profile_str} CANDIDATE] {title}")

            # Step D: Web Search Sanity Check & Quant Filter
            if is_candidate:
                ticker = release.ticker

                # Step D1: Web Search Verification (Reverse splits, dilution, regulatory red flags)
                if ticker:
                    web_res = self.web_verifier.verify(ticker=ticker, company_name=release.company_name or "")
                    if not web_res.get("passed_web_check", True):
                        reason = web_res.get("reason", "Failed web sanity check")
                        logger.info(f"[-] Rejected by Web Sanity Check ({ticker}): {reason}")
                        if not dry_run:
                            mark_as_processed(article_id, title, pub_date, self.config.db_path)
                        continue

                spread_pct = None
                bid = None
                ask = None
                volume = 0
                entry_price = 10.0  # Default fallback if quote unavailable

                if ticker:
                    liquidity_res = check_liquidity_and_spread(
                        ticker=ticker,
                        max_spread_pct=self.config.max_bid_ask_spread_pct,
                        min_volume=2000,
                        commission_min_eur=self.config.nordnet_min_commission_eur,
                        commission_percent=self.config.nordnet_commission_percent,
                        sample_trade_size_eur=self.config.nordnet_min_trade_eur * 2.0,
                        max_total_friction_pct=self.config.max_total_friction_pct,
                    )
                    spread_pct = liquidity_res.get("spread_pct")
                    bid = liquidity_res.get("bid")
                    ask = liquidity_res.get("ask")
                    volume = liquidity_res.get("volume", 0)
                    total_friction_pct = liquidity_res.get("total_friction_pct")
                    comm_round_trip = liquidity_res.get("commission_round_trip_eur", 14.0)
                    min_trade = liquidity_res.get("min_recommended_trade_eur", self.config.nordnet_min_trade_eur)
                    if ask and ask > 0:
                        entry_price = ask
                    elif bid and bid > 0:
                        entry_price = bid

                    if not liquidity_res["passed_spread_check"]:
                        logger.info(f"[-] Rejected by Quant Friction Filter ({ticker}): {liquidity_res['reason']}")
                        if not dry_run:
                            mark_as_processed(article_id, title, pub_date, self.config.db_path)
                        continue
                else:
                    total_friction_pct = None
                    comm_round_trip = 14.0
                    min_trade = self.config.nordnet_min_trade_eur

                # Calculate Sizing
                sizing = self.calculate_sizing(strategy_route, ticker or "", min_trade)
                alloc_eur = sizing["recommended_allocation_eur"]
                shares_to_buy = max(1, int(alloc_eur / entry_price)) if entry_price > 0 else 100

                candidate = {
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                    "company_name": release.company_name or "Unknown",
                    "ticker": ticker or "",
                    "strategy_type": strategy_route,
                    "title": title,
                    "link": release.link,
                    "signals": signal_label,
                    "reasoning": educational_rationale,
                    "recommended_allocation_eur": alloc_eur,
                    "kelly_fraction": sizing.get("kelly_fraction"),
                    "sizing_model": sizing["sizing_model"],
                    "spread_pct": spread_pct,
                    "bid": bid,
                    "ask": ask,
                    "volume": volume,
                    "total_friction_pct": total_friction_pct,
                    "commission_round_trip_eur": comm_round_trip,
                    "min_recommended_trade_eur": min_trade,
                    "pdf_attached": len(doc.pdf_urls) > 0,
                    "entry_price": entry_price,
                    "shares": shares_to_buy,
                    "management_buying": signals.get("insider_buying_personal", signals.get("management_buying", False)),
                    "positive_guidance": signals.get("positive_guidance", False),
                    "insider_buying_personal": signals.get("insider_buying_personal", False),
                    "company_share_buyback": signals.get("company_share_buyback", False),
                    "cash_issue": safety_failed,
                }
                candidates_found.append(candidate)

                self._print_alert(candidate)

                # Step E: Execute & Alert
                if not dry_run:
                    self._append_to_csv(candidate)
                    if ticker:
                        self.record_open_position(
                            candidate=candidate,
                            entry_price=entry_price,
                            shares=shares_to_buy,
                            position_value=alloc_eur,
                        )
                    try:
                        send_alert(
                            pipeline_type=strategy_route,
                            ticker=candidate["ticker"],
                            company_name=candidate["company_name"],
                            analysis_summary=candidate,
                            email_client=self.email_client,
                        )
                    except Exception as email_err:
                        logger.debug(f"Email notification error: {email_err}")

            if not dry_run:
                mark_as_processed(article_id, title, pub_date, self.config.db_path)

        elapsed = time.time() - start_time
        logger.info("=" * 75)
        logger.info(
            f"Screening cycle finished in {elapsed:.2f}s. "
            f"({skipped_count} skipped, {trash_count} trash noise discarded, "
            f"{universe_discard_count} outside-universe filtered, "
            f"{processed_count} evaluated, {len(candidates_found)} alerts)"
        )
        logger.info("=" * 75)

        return candidates_found

    # Compatibility alias for existing tests
    def run_pipeline_cycle(self, dry_run: bool = False) -> List[Dict[str, Any]]:
        return self.run_screening_cycle(dry_run=dry_run)

    def run_eod_maintenance(self, dry_run: bool = False) -> List[Dict[str, Any]]:
        """
        End-of-Day maintenance routine (Run daily at 19:00):
        1. Evaluates all open paper positions with ExitManager.
        2. Closed trades are moved to trade_history.csv.
        3. Dispatches automated [SELL ALERT] emails.
        """
        logger.info("\n" + "=" * 80)
        logger.info(">>> RUNNING END-OF-DAY (EOD) MAINTENANCE & EXIT MANAGEMENT <<<")
        logger.info("=" * 80)

        eod_res = self.exit_manager.check_exits()
        closed_trades = eod_res.get("closed_trades", []) if isinstance(eod_res, dict) else (eod_res or [])

        if not closed_trades:
            logger.info("No position exits triggered today. All positions held.")
            return []

        logger.info(f"✅ Executed {len(closed_trades)} position exit(s):")
        for trade in closed_trades:
            ticker = trade["Ticker"]
            strat = trade.get("Strategy_Type", "SATELLITE")
            net_ret = trade.get("NetReturnPct", 0.0)
            reason = trade.get("ExitReason", "")
            logger.info(f" -> [EXIT] {ticker} ({strat}): Net PnL {net_ret:+.2f}% | Reason: {reason}")

            if not dry_run:
                try:
                    send_sell_alert(
                        ticker=ticker,
                        strategy_type=strat,
                        trade_data=trade,
                        email_client=self.email_client,
                    )
                except Exception as e:
                    logger.warning(f"Failed to dispatch sell alert email for {ticker}: {e}")

        return closed_trades

    def _print_alert(self, candidate: Dict[str, Any]) -> None:
        """Print highlighted alert to console."""
        strat = candidate.get("strategy_type", "SATELLITE")
        spread_info = (
            f"{candidate['spread_pct']}% (Bid: {candidate['bid']} / Ask: {candidate['ask']})"
            if candidate.get("spread_pct") is not None
            else "N/A"
        )
        friction_info = (
            f"{candidate['total_friction_pct']}% (Nordnet kulu: {candidate.get('commission_round_trip_eur')} EUR)"
            if candidate.get("total_friction_pct") is not None
            else "N/A"
        )
        tag = "[ALERT: CORE 10-BAGGER CANDIDATE]" if strat == StrategyType.CORE.value else "[ALERT: SATELLITE CATALYST HUNTING]"
        
        print("\n" + "=" * 80)
        print(f"{tag} {candidate['company_name']} ({candidate['ticker'] or 'N/A'})")
        print(f"Strategy:       {strat}")
        print(f"Signals:        {candidate['signals']}")
        print(f"Position Size:  {candidate['recommended_allocation_eur']:.0f} EUR ({candidate['sizing_model']})")
        print(f"Spread:         {spread_info} | Vol: {candidate.get('volume', 'N/A')}")
        print(f"Friction:       {friction_info} | Min. ostosuositus: >= {candidate.get('min_recommended_trade_eur', 500):.0f} EUR")
        print(f"Title:          {candidate['title']}")
        print(f"Link:           {candidate['link']}")
        print(f"PDF Attached:   {'Yes' if candidate['pdf_attached'] else 'No'}")
        if candidate.get("reasoning"):
            print(f"Pedagoginen Perustelu:\n  👉 {candidate['reasoning']}")
        print("=" * 80 + "\n")

    def _append_to_csv(self, candidate: Dict[str, Any]) -> None:
        """Append candidate record to screener_alerts.csv."""
        file_exists = self.alerts_csv_path.exists()
        fieldnames = [
            "timestamp", "company_name", "ticker", "strategy_type", "title",
            "link", "signals", "recommended_allocation_eur", "kelly_fraction", "sizing_model",
            "reasoning", "spread_pct", "bid", "ask", "volume",
            "total_friction_pct", "commission_round_trip_eur", "min_recommended_trade_eur",
            "management_buying", "positive_guidance", "pdf_attached"
        ]
        try:
            with open(self.alerts_csv_path, "a", newline="", encoding="utf-8") as f:
                writer = csv.writer(f)
                if not file_exists:
                    writer.writerow(fieldnames)
                writer.writerow([
                    candidate["timestamp"],
                    candidate["company_name"],
                    candidate["ticker"],
                    candidate.get("strategy_type", "SATELLITE"),
                    candidate["title"],
                    candidate["link"],
                    candidate["signals"],
                    candidate.get("recommended_allocation_eur", ""),
                    candidate.get("kelly_fraction", ""),
                    candidate.get("sizing_model", ""),
                    candidate.get("reasoning", ""),
                    candidate.get("spread_pct", ""),
                    candidate.get("bid", ""),
                    candidate.get("ask", ""),
                    candidate.get("volume", ""),
                    candidate.get("total_friction_pct", ""),
                    candidate.get("commission_round_trip_eur", ""),
                    candidate.get("min_recommended_trade_eur", ""),
                    candidate["management_buying"],
                    candidate["positive_guidance"],
                    candidate["pdf_attached"],
                ])
        except Exception as e:
            logger.error(f"Failed to append alert to {self.alerts_csv_path}: {e}")


def main():
    parser = argparse.ArgumentParser(
        description="Nordic Micro-Cap Core & Satellite Screener & Trading Bot v2.0.0"
    )
    parser.add_argument(
        "--version",
        action="version",
        version="tradeBotTiuku Core & Satellite Screener v2.0.0"
    )
    parser.add_argument(
        "--run-once",
        action="store_true",
        help="Run the screening pipeline once and exit"
    )
    parser.add_argument(
        "--loop",
        action="store_true",
        help="Run continuous background daemon loop (with dynamic asymmetric scraping)"
    )
    parser.add_argument(
        "--interval",
        type=int,
        default=None,
        help="Explicit fixed polling interval in seconds (overrides asymmetric dynamic schedule)"
    )
    parser.add_argument(
        "--peak-interval",
        type=int,
        default=40,
        help="Polling interval in seconds during morning peak rush 08:30-10:00 (default: 40s)"
    )
    parser.add_argument(
        "--regular-interval",
        type=int,
        default=300,
        help="Polling interval in seconds during regular day hours 08:00-18:30 (default: 300s = 5 min)"
    )
    parser.add_argument(
        "--offmarket-interval",
        type=int,
        default=900,
        help="Polling interval in seconds outside market hours and weekends (default: 900s = 15 min)"
    )
    parser.add_argument(
        "--check-exits",
        action="store_true",
        help="Run End-of-Day exit maintenance on open positions and exit"
    )
    parser.add_argument(
        "--universe",
        type=str,
        default=str(DEFAULT_UNIVERSE_CSV),
        help=f"Path to Nordnet universe CSV file (default: {DEFAULT_UNIVERSE_CSV})"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Execute without persisting positions or state"
    )
    args = parser.parse_args()

    controller = ScreenerPipelineController(universe_csv_path=args.universe)

    if args.check_exits:
        controller.run_eod_maintenance(dry_run=args.dry_run)
        return

    if args.loop:
        # Override config interval values if passed
        controller.config.peak_interval_seconds = args.peak_interval
        controller.config.regular_interval_seconds = args.regular_interval
        controller.config.offmarket_interval_seconds = args.offmarket_interval

        if args.interval is not None:
            logger.info(f"Starting continuous daemon loop with FIXED interval: {args.interval}s...")
        else:
            logger.info(
                f"Starting continuous daemon loop with ASYMMETRIC dynamic schedule "
                f"(Peak 08:30-10:00: {args.peak_interval}s, Day: {args.regular_interval}s, Off-market: {args.offmarket_interval}s)..."
            )

        last_eod_date = None
        try:
            while True:
                now = datetime.now()
                # Run regular intraday screening cycle
                controller.run_screening_cycle(dry_run=args.dry_run)

                # Check if it's EOD maintenance time (19:00+) and hasn't run today
                today = now.date()
                if now.hour >= 19 and last_eod_date != today:
                    logger.info("19:00 reached: Triggering scheduled End-of-Day maintenance...")
                    controller.run_eod_maintenance(dry_run=args.dry_run)
                    last_eod_date = today

                if args.interval is not None:
                    sleep_sec = args.interval
                    mode_desc = f"Fixed interval ({sleep_sec}s)"
                else:
                    sleep_sec, mode_desc = get_dynamic_interval(datetime.now(), controller.config)

                logger.info(f"Heartbeat OK | Schedule Mode: {mode_desc} | Next cycle in {sleep_sec}s...")
                time.sleep(sleep_sec)
        except KeyboardInterrupt:
            logger.info("Daemon loop terminated by user (KeyboardInterrupt). Exiting cleanly.")
    else:
        controller.run_screening_cycle(dry_run=args.dry_run)


if __name__ == "__main__":
    main()
