"""
Data models for the stock screener pipeline.
"""

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import List, Dict, Optional, Any


class ProcessingStatus(str, Enum):
    NEW = "NEW"
    PARSED = "PARSED"
    NLP_ANALYZED = "NLP_ANALYZED"
    QUANT_PASSED = "QUANT_PASSED"
    QUANT_REJECTED = "QUANT_REJECTED"
    ALERTED = "ALERTED"
    ERROR = "ERROR"


@dataclass
class FeedItem:
    """Represents an individual item parsed from an RSS feed."""
    guid: str
    title: str
    link: str
    published_at: Optional[datetime] = None
    summary: str = ""
    company_name: Optional[str] = None
    ticker: Optional[str] = None
    category: Optional[str] = None
    source_feed: Optional[str] = None
    raw_metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class DocumentPayload:
    """Contains text and attachment data parsed from HTML or PDF."""
    url: str
    html_text: str = ""
    pdf_text: str = ""
    pdf_urls: List[str] = field(default_factory=list)
    extracted_tables: List[List[List[str]]] = field(default_factory=list)
    error_message: Optional[str] = None
    
    @property
    def full_combined_text(self) -> str:
        """Combine HTML body and attached PDF text."""
        parts = []
        if self.html_text.strip():
            parts.append(self.html_text.strip())
        if self.pdf_text.strip():
            parts.append("--- ATTACHED PDF REPORT CONTENT ---\n" + self.pdf_text.strip())
        return "\n\n".join(parts)


@dataclass
class ScrapedRelease:
    """Aggregated release container combining RSS metadata and extracted document content."""
    feed_item: FeedItem
    document: DocumentPayload
    status: ProcessingStatus = ProcessingStatus.PARSED
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    
    @property
    def id(self) -> str:
        return self.feed_item.guid


@dataclass
class NLPExtractionResult:
    """Structured extraction results generated by LLM analysis."""
    release_id: str
    ticker: Optional[str] = None
    company_name: Optional[str] = None
    
    # 1. Cash flow issues or need for new funding
    has_cash_flow_issues: bool = False
    funding_need_explanation: str = ""
    
    # 2. Management buying/selling shares (MAR Art 19 / Insider transactions)
    has_management_transactions: bool = False
    transaction_direction: Optional[str] = None  # "BUY", "SELL", "NONE"
    transaction_details: str = ""
    
    # 3. Positive profit warning / guidance upgrade
    is_positive_profit_warning: bool = False
    guidance_change_summary: str = ""
    
    confidence_score: float = 1.0
    raw_llm_response: Optional[str] = None


@dataclass
class ScreeningCandidate:
    """Complete evaluated candidate that passes or fails quant risk filters."""
    release: ScrapedRelease
    nlp_result: NLPExtractionResult
    
    # Quantitative Risk Metrics
    cash_runway_months: Optional[float] = None
    bid_ask_spread_pct: Optional[float] = None
    current_cash_eur: Optional[float] = None
    quarterly_burn_rate_eur: Optional[float] = None
    latest_price_eur: Optional[float] = None
    
    passed_filters: bool = False
    rejection_reasons: List[str] = field(default_factory=list)
