"""
Trailing Stop-Loss Simulation Engine for Trade Execution Validation.

Simulates and backtests the execution of a 20% mechanical trailing stop-loss
on historical BUY signals generated by fundamental_backtester.py.
Compares unmanaged 6-month returns (Buy & Hold) vs. managed returns with trailing stop.
"""

from __future__ import annotations

import argparse
import logging
import sys
from dataclasses import dataclass, asdict
from datetime import datetime, timedelta
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Any

import numpy as np
import pandas as pd
import yfinance as yf

# Configure cross-platform terminal encoding (Windows cp1252 fix)
if hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass
if hasattr(sys.stderr, "reconfigure"):
    try:
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)]
)
logger = logging.getLogger("stop_loss_simulator")


@dataclass
class TradeSimulationResult:
    ticker: str
    buy_date: str
    buy_price: float
    profile: str
    unmanaged_return_pct: Optional[float]
    managed_return_pct: float
    exit_type: str  # "STOP_LOSS" or "6M_EXPIRY"
    sell_date: str
    sell_price: float
    highest_seen: float
    max_drawdown_managed_pct: float
    holding_days: int


def calculate_atr(df: pd.DataFrame, period: int = 14) -> pd.Series:
    """
    Calculates 14-day Average True Range (ATR) using Daily High, Low, and Close prices.
    TR = max(High - Low, |High - Close_prev|, |Low - Close_prev|)
    """
    high = df["High"]
    low = df["Low"]
    close_prev = df["Close"].shift(1)

    tr1 = high - low
    tr2 = (high - close_prev).abs()
    tr3 = (low - close_prev).abs()

    tr = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)
    atr = tr.rolling(window=period, min_periods=period).mean()
    return atr


class StopLossSimulator:
    """
    Simulates a dynamic 2.5x ATR trailing stop-loss on historical buy signals.
    """

    def __init__(
        self,
        signals_csv: str = "data/institutional_backtest_results.csv",
        atr_multiplier: float = 2.5,
        atr_period: int = 14,
        trailing_stop_pct: float = 20.0,  # kept for backwards compatibility
        holding_period_days: int = 126,  # approx 6 months of trading days (~180 calendar days)
    ):
        self.signals_csv = Path(signals_csv)
        self.atr_multiplier = atr_multiplier
        self.atr_period = atr_period
        self.trailing_stop_pct = trailing_stop_pct
        self.holding_period_days = holding_period_days

        # In-memory price cache to avoid redundant yfinance downloads
        self._price_cache: Dict[str, pd.DataFrame] = {}

    def fetch_price_history(self, ticker: str) -> Optional[pd.DataFrame]:
        """Fetches daily price history with caching and error handling."""
        cleaned_ticker = ticker.strip().upper()
        if cleaned_ticker in self._price_cache:
            return self._price_cache[cleaned_ticker]

        try:
            t = yf.Ticker(cleaned_ticker)
            df = t.history(period="10y", auto_adjust=True)
            if df.empty:
                logger.warning(f"No price history returned for {cleaned_ticker}")
                return None
            df.index = pd.to_datetime(df.index).tz_localize(None)
            df = df.sort_index()

            # Precalculate 14-day ATR across the full historical dataset
            df["ATR_14"] = calculate_atr(df, period=self.atr_period)

            self._price_cache[cleaned_ticker] = df
            return df
        except Exception as e:
            logger.warning(f"Failed to fetch prices for {cleaned_ticker}: {e}")
            return None

    def simulate_trade(
        self,
        ticker: str,
        buy_date_str: str,
        profile: str = "N/A",
        expected_unmanaged_ret: Optional[float] = None
    ) -> Optional[TradeSimulationResult]:
        """
        Simulates a single trade chronologically over 6 months (~126 trading days)
        using a 2.5x ATR dynamic trailing stop.
        """
        price_df = self.fetch_price_history(ticker)
        if price_df is None or price_df.empty:
            return None

        buy_dt = pd.to_datetime(buy_date_str).tz_localize(None)
        sub_df = price_df[price_df.index >= buy_dt]
        if sub_df.empty:
            logger.warning(f"No price data found for {ticker} on or after {buy_date_str}")
            return None

        # Take up to holding_period_days + 1 trading days
        window_df = sub_df.iloc[: min(len(sub_df), self.holding_period_days + 1)]
        if len(window_df) < 1:
            return None

        # Day 1 Initialization
        day1 = window_df.iloc[0]
        buy_price = float(day1["Close"])
        if buy_price <= 0:
            return None

        actual_buy_date = window_df.index[0].strftime("%Y-%m-%d")

        # Day 1 ATR calculation
        atr_14 = float(day1["ATR_14"]) if pd.notna(day1["ATR_14"]) and day1["ATR_14"] > 0 else (buy_price * 0.08)

        # Initial Stop: On buy date, trailing_stop = buy_price - (2.5 * ATR_14)
        initial_stop = max(0.0001, buy_price - (self.atr_multiplier * atr_14))
        trailing_stop = initial_stop
        highest_seen_close = buy_price

        stopped_out = False
        sell_date = None
        sell_price = None
        max_seen_drawdown = 0.0

        # Iterate over subsequent trading days
        for i in range(1, len(window_df)):
            day = window_df.iloc[i]
            day_date = window_df.index[i].strftime("%Y-%m-%d")
            low_px = float(day["Low"])
            high_px = float(day["High"])
            close_px = float(day["Close"])
            open_px = float(day["Open"])
            cur_atr = float(day["ATR_14"]) if pd.notna(day["ATR_14"]) and day["ATR_14"] > 0 else atr_14

            # Calculate current drawdown from entry
            current_entry_dd = (low_px - buy_price) / buy_price * 100.0
            if current_entry_dd < max_seen_drawdown:
                max_seen_drawdown = current_entry_dd

            # TRIGGER SELL if daily Low drops below or hits trailing_stop
            if low_px <= trailing_stop:
                stopped_out = True
                sell_date = day_date
                # Execution at trailing stop level (or open if gapped down)
                sell_price = min(open_px, trailing_stop) if open_px < trailing_stop else trailing_stop
                exit_type = "ATR_STOP_LOSS"
                break

            # Trailing Logic: For every subsequent day, calculate new 2.5x ATR.
            # If current_close > highest_seen_close:
            # new_stop = current_close - (2.5 * current_ATR_14)
            # The trailing stop can only move UP, never down.
            if close_px > highest_seen_close:
                highest_seen_close = close_px
                new_stop = close_px - (self.atr_multiplier * cur_atr)
                if new_stop > trailing_stop:
                    trailing_stop = new_stop

        # Expiry at end of 6 months if not stopped out
        if not stopped_out:
            last_day = window_df.iloc[-1]
            sell_date = window_df.index[-1].strftime("%Y-%m-%d")
            sell_price = float(last_day["Close"])
            exit_type = "6M_EXPIRY"

        managed_ret_pct = round(((sell_price - buy_price) / buy_price) * 100.0, 2)
        
        # Unmanaged 6-month return (from last day of window)
        final_close = float(window_df.iloc[-1]["Close"])
        unmanaged_calc_ret = round(((final_close - buy_price) / buy_price) * 100.0, 2)
        unmanaged_ret = expected_unmanaged_ret if (expected_unmanaged_ret is not None and not np.isnan(expected_unmanaged_ret)) else unmanaged_calc_ret

        holding_days = (pd.to_datetime(sell_date) - pd.to_datetime(actual_buy_date)).days

        return TradeSimulationResult(
            ticker=ticker,
            buy_date=actual_buy_date,
            buy_price=round(buy_price, 2),
            profile=profile,
            unmanaged_return_pct=unmanaged_ret,
            managed_return_pct=managed_ret_pct,
            exit_type=exit_type,
            sell_date=sell_date,
            sell_price=round(sell_price, 2),
            highest_seen=round(highest_seen_close, 2),
            max_drawdown_managed_pct=round(max_seen_drawdown, 2),
            holding_days=holding_days,
        )

    def run(self) -> Tuple[pd.DataFrame, pd.DataFrame]:
        """
        Executes stop-loss simulation across all signals in signals_csv.
        Returns:
            (trades_df, comparison_summary_df)
        """
        if not self.signals_csv.exists():
            raise FileNotFoundError(f"Signals file not found at: {self.signals_csv}")

        signals_df = pd.read_csv(self.signals_csv)
        logger.info(f"Loaded {len(signals_df)} historical buy signals from {self.signals_csv}")

        results: List[TradeSimulationResult] = []

        for idx, row in signals_df.iterrows():
            ticker = str(row["ticker"]).strip().upper()
            buy_date = str(row.get("buy_date") or row.get("report_date")).strip()
            profile = str(row.get("profile", "N/A"))
            unmanaged_ret = row.get("return_6m_pct", row.get("unmanaged_return_pct", None))
            if pd.isna(unmanaged_ret):
                unmanaged_ret = None
            else:
                unmanaged_ret = float(unmanaged_ret)

            sim_res = self.simulate_trade(
                ticker=ticker,
                buy_date_str=buy_date,
                profile=profile,
                expected_unmanaged_ret=unmanaged_ret
            )
            if sim_res:
                results.append(sim_res)

        trades_df = pd.DataFrame([asdict(r) for r in results])
        summary_df = self._generate_summary(trades_df)
        return trades_df, summary_df

    def _generate_summary(self, df: pd.DataFrame) -> pd.DataFrame:
        """Generates statistical comparison between Unmanaged and Managed strategies."""
        if df.empty:
            return pd.DataFrame()

        # Filter valid rows
        valid_unmanaged = df["unmanaged_return_pct"].dropna()
        valid_managed = df["managed_return_pct"].dropna()

        # Counts
        total_trades = len(df)
        stop_loss_triggered = (df["exit_type"].astype(str).str.contains("STOP_LOSS")).sum()
        expiry_held = (df["exit_type"] == "6M_EXPIRY").sum()

        # Win Rates
        win_rate_unmanaged = (valid_unmanaged > 0).mean() * 100.0 if not valid_unmanaged.empty else 0.0
        win_rate_managed = (valid_managed > 0).mean() * 100.0 if not valid_managed.empty else 0.0

        # Average Returns
        avg_ret_unmanaged = valid_unmanaged.mean() if not valid_unmanaged.empty else 0.0
        avg_ret_managed = valid_managed.mean() if not valid_managed.empty else 0.0

        # Median Returns
        median_ret_unmanaged = valid_unmanaged.median() if not valid_unmanaged.empty else 0.0
        median_ret_managed = valid_managed.median() if not valid_managed.empty else 0.0

        # Worst Return (Maximum Loss realized)
        worst_loss_unmanaged = valid_unmanaged.min() if not valid_unmanaged.empty else 0.0
        worst_loss_managed = valid_managed.min() if not valid_managed.empty else 0.0

        # Best Return
        best_ret_unmanaged = valid_unmanaged.max() if not valid_unmanaged.empty else 0.0
        best_ret_managed = valid_managed.max() if not valid_managed.empty else 0.0

        # Average Holding Days
        avg_holding_days = df["holding_days"].mean() if not df.empty else 0.0

        summary_data = [
            {
                "Strategy / Metric": "Unmanaged (6M Buy & Hold)",
                "Total Trades": total_trades,
                "Win Rate (%)": f"{win_rate_unmanaged:.2f}%",
                "Avg Return (%)": f"{avg_ret_unmanaged:.2f}%",
                "Median Return (%)": f"{median_ret_unmanaged:.2f}%",
                "Max Loss / Worst Trade (%)": f"{worst_loss_unmanaged:.2f}%",
                "Best Trade (%)": f"{best_ret_unmanaged:.2f}%",
                "Stop-Loss Triggers": "0 (N/A)",
                "Avg Holding (Days)": f"~180 days",
            },
            {
                "Strategy / Metric": f"Managed ({self.atr_multiplier:.1f}x ATR Trailing Stop)",
                "Total Trades": total_trades,
                "Win Rate (%)": f"{win_rate_managed:.2f}%",
                "Avg Return (%)": f"{avg_ret_managed:.2f}%",
                "Median Return (%)": f"{median_ret_managed:.2f}%",
                "Max Loss / Worst Trade (%)": f"{worst_loss_managed:.2f}%",
                "Best Trade (%)": f"{best_ret_managed:.2f}%",
                "Stop-Loss Triggers": f"{stop_loss_triggered} ({stop_loss_triggered/total_trades*100:.1f}%)",
                "Avg Holding (Days)": f"{avg_holding_days:.1f} days",
            }
        ]

        return pd.DataFrame(summary_data)


# ----------------------------------------------------------------------
# CLI ENTRY POINT & REPORTING
# ----------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Stop-Loss Simulator: Test 2.5x ATR Dynamic Trailing Stop on fundamental buy signals."
    )
    parser.add_argument(
        "--signals",
        default="data/institutional_backtest_results.csv",
        help="Path to fundamental signals CSV file.",
    )
    parser.add_argument(
        "--atr-multiplier",
        type=float,
        default=2.5,
        help="ATR stop-loss multiplier (default: 2.5).",
    )
    parser.add_argument(
        "--atr-period",
        type=int,
        default=14,
        help="ATR rolling window period in trading days (default: 14).",
    )
    parser.add_argument(
        "--output",
        default="data/stop_loss_simulation_results.csv",
        help="Path to save trade simulation results CSV.",
    )

    args = parser.parse_args()

    simulator = StopLossSimulator(
        signals_csv=args.signals,
        atr_multiplier=args.atr_multiplier,
        atr_period=args.atr_period,
    )

    trades_df, summary_df = simulator.run()

    print("\n" + "=" * 90)
    print(f"🛡️ DYNAMIC ATR TRAILING STOP-LOSS REPORT ({args.atr_multiplier:.1f}x ATR, {args.atr_period}d)")
    print("=" * 90)

    if not summary_df.empty:
        print(summary_df.to_string(index=False))
    else:
        print("No simulation summary available.")

    print("\n" + "=" * 90)
    print("📋 SAMPLE DETAILED TRADES (FIRST 15)")
    print("=" * 90)

    if not trades_df.empty:
        display_cols = [
            "ticker", "buy_date", "buy_price", "unmanaged_return_pct",
            "managed_return_pct", "exit_type", "sell_date", "sell_price", "holding_days"
        ]
        print(trades_df[display_cols].head(15).to_string(index=False))

        # Save to CSV
        try:
            trades_df.to_csv(args.output, index=False)
            print(f"\nSaved {len(trades_df)} simulation records to {args.output}")
        except Exception as e:
            logger.error(f"Failed to save CSV to {args.output}: {e}")
    else:
        print("No trades simulated.")


if __name__ == "__main__":
    main()
